---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres
  namespace: todo-app
spec:
  encryptedData:
    password: AgCN5rusKitNMyoxSLcBw/SU7NsoB/6elXcWGiEXPYn+vgEGavOY18/nLIwl1Hb+izGNqiZ9M7CZsXlN5KYXT/HBkXgbWj3n2IMo8htGDxx42DrJFoLF4Up21C1vCOYLDU4OCsUZXs7zsRGtRzSnd9vuXH2xW2rk47dOpPZWUKMbx5Tvzhsj3pdODGqAvSeir0ldUsMVVSnRT2ftX3jz314y9BDCcAdZDTcmDzF+m2vF2lrREwAQokIKTbZY/+9TQ44kkwDXwkOCvfQZ6NelvEeUg0yP/66oPTGVgrhfxx/hTZBFudtiGeRtgXyJTfcVZXWib9aW8y1JdJnSlEsu09egNTlEId5SR9Ao8mVahVkvelw/yN4aiulBYHTQpRmq4WHs3GYk4pOTWcBNc+3PnGhYstTvSkNlJBNOqpNT+OaqWBi7K1gUuHdgu2yaiHLPQgHghMX639xCkqQoija9CJKpRSdH31RueIokQWhZDR2J1MBfmveHvdJa69IfQuIVBfzXQxvfthXPyCCE4c7+TdO+6BLfAx+4CdjIEWJ1cfPzlyuwJpEWQ9NGIFTVGiCwX+NpbL2rZCaG3EHnNNsdlvpuItDermr3U4r3ABCRTTyt1ebJVQHvMNYlYuUbhxFQwc7DJkNAkP+BXbYSktZPUfjh5y0ddrORORecXNn/yJc/hUMy2flxAtu4hybxkU0BH/ZGh277NHHnFFKJx11UGF0C4LuqICsRSjus7JqK+Jw47NRvXTJH135nHUgKTQ==
    username: AgCuHA9ZSvvIeZKoe4r0xcYe60OIADVMev3peIUdfJXXg2et0BuQB262LodshdFx79QAZMH2lEh+QAH6lAKlQV8g0Scs7s83qGcNqLhOcTTB6SAoShJ7DFrgAa+fYKISVYIsi8ynlT0vkkH38DNbF0Ff7vcNpxjAyHwt/JgCrs+ecdt45HtiZEdvvjeTvNGjrRX+asGkC/QiRyGTa2i4iIDLQ2JLghtVWjHgI+wiQSDtaDmwCF6QXs7OaJRjOrfW1GTXN5o+snNkKvq+Ez7WA+AYLuoMUwwMHnnJye8q03F2VlC5IwbelnveJL3I6V8nLurPZllzAIOWr394eHILhRe6Xw9lTGgvoQNH5oFJEc8b4mijJRjxU/dUYY5yNXvZTP4hn/7yhTUzBN8Asi4I8pnz1gtaFBa3uwGlmke9xZTY+fNMppOwx2DOWgdBMGqFqZGPPcrJuggtNCKkdJeyR1U7gvBdEfCU2rAcKDH875t3qF15D8gzttilQ9c13Bw7d9WqvjGXyf53DsCEt6lXU8KvANn9BUMkPcg6z+FFv+cSS74J7qTYykn0H3yyqUbgVKVJkGh3KL7wsvlHBoKbEt9HFyionV/AWMDR+CUGTFD4kUb/a4bdR6/aB2fu+qAJEOAjnu892RR07zyvYkqgb0UQsNrgnJi5cMqJK4m0qaoK03iXfFvreg65xuwDfj8YDA717pvz9LFp
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: todo-app
      name: postgres
      namespace: todo-app
    type: Opaque
