---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres
  namespace: todo-app
spec:
  encryptedData:
    password: AgBo2k//jROFXEEfYFx8AKoWcr33lEfQKeYPyPtYu4N0/Qe/8X/DS0Pb6+hd7G/KcLpT6Y8P+uRf2exNyBF2CogYlbmMzHHd+UAdNL/10bkS4xBYph/qPHUH/rjkuw9ek81uBycwQs71nC9tMxf/S+aGDaKUyJn+Fae45nw2SIJ/MxOfLB03/43tKYoSHSvrxoJM6PoVFv1RSq2iEYBO7Y4leXD60apOUuOOytGKLg/hUWUnRgoDcQw/B3VNyx9gQD0oNnxbWu5nF1w7mksZUUVEgSEXJBR0H99I1IVauKjIGPDmugjNZ/s4LkhHPXpSZs2UNFx/3ckXrDLMeopTXVIHNqcmxyUw1wBP0f+NJ/sGqugtzQX1GeLWq2JQzmX0TPA4aUs61dCpeU9aU/UbP7QCLWtPf0exZSjy/QFWAvjqmRZa3p3aKBp+wMb8utI7VT4jnZF3WsunfrNOdU/asGo1R4eebpvkFp4pWc1Fg9hgV+SEVrkK9fzSsHP8jj3pZAJptlqrd6mhWeGUZJcXHxzKr6j79EgTSTuJb/x2WdPxSj69W+diQE7RMIzWskAT/nuu2IEZ+z28Ohi/S2U9MmGhtZWOC+xJ84U54Oll7KSly8rKflVyLif11F9ZidDasdKKsn/Fc3D5oVZn/1UFHYsH+bmpFvQnQY+cumbfoGYyvAjlmOgEV8YW/iCX3DcrTrPfmLbrvKsugBLQP9xADJ9VDmaLIWp2ZTxrN1riZqpf+TfXzKSZaGX1+s9HsQ==
    username: AgBgior7tXI3pWuLGWbJJ1dqNL6ElKSLncPm8FbTSh466mReIeq7r12pFGKLFNLmEL3eYJkKdWydPvqohxbNjtgF6ei/Rzy/iBhyTkEubrK6rp07Gk8NIKmVoXVVWwMpjKhr2m3l8oo5j1ba2UWipP4EUHspOXpDBf3thy35fxLGT3OVvU4NbMzch/+RQk544UQ2i79glJb57+eANlidQkV3zlQIh+Ub5lDD5Pb76JZwSjNto+zbteiMcxkD7YIXjDWMFBhzah6/ifr/dqPECmrL+ngTn/tTM8a50gSFy25lhWE6JhB0UPYZ9/SsO6ZFI2QZ1iuc67e/0yO7ROe7GcCsjxssnFY+U23N7x4ihqIbW+uqLTqo9EJEFIe23I4mP208EtJ4QPo/NbKoQ1npdnK63PAoJRgPt70gIt8WYXhyH/mtKJrGcKlkIeXj2RCEyaNmW9lUeHNAx/IxAN7lPMd+ez9m9ITMNGthMskwY45Ej+YysqJZrjYWARlpR8kMD4LAnFr8ZJxbwMua1xr4e8zffHFBPU7BhWZsjHSzvOX6Yn9BXmXidClHlKPi6eKT1VfiueODW7pGQItyFNaMTFXe7BOptKzcITiMKmdp5pbDrRQkslmXh8qrR5FrFAYtisYfLKYt3Zd4Amh2HClauQXCTiI5IbPhmvAuxE+/XmdZQ1JU1KYJOSrDWYvOyQD5NHscpqY8fMc4
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: todo-app
      name: postgres
      namespace: todo-app
    type: Opaque
