---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: todo-app
spec:
  encryptedData:
    .dockerconfigjson: AgBRlVACmMGThwlj+L91j3/Dazkdk+p+rMUyI8WvzmYg5HCjZBSRiM+rfjOqtmaNg2lMJCiez9cV5r0BTzQ4cB2qh632jhiX5fJ58Ljp2VGk2A1+Wg1ZMe5e0dCz7I9pP7JTscNYbMiCi4AwPfD487adnkrAw/W1+LoOjnz6/LycjO7vvUSco2g1+GAiFvc6mJRAiYUAT7Qw6MHs2Zn8jeYL0U7xjmM8kQ55g8RlW9pw0zVeoDBUNb/NlvN6M+xxa/aRPQXscqw38Vj1m2BZWaxQ95xdWJBr1L2flS2q8ecNRXRuhl1i2584T+UEidkTwylLMwPY6/LyLis0d9uNveQ0jIqReNZOAP6gcjinWjzprNU1JycV1EiDlNUSiV2e2zW7UGRcTkQaSAHJr0lE4BIuhIvVmMCsxtNmNUrx1a98bWXQlioLE3ep4rHoVDKNwSeMDNTnVRmOGHczol1JlEt5nWgpjPiNwMH6IL717fAA0XGHRjNR+2qUGZcRRh+zCqJHWurWvudXkiYbb0ZTgkrZXh/VE3/E/VYtQPmKdB4DE/4qlQqX0R2sJwOywwApgNKZnTR0znQRQUQZEjWQLCZrBq5B78983gDixUBkWTCjytGMDDnj2i4kR10Hmg7lJeoY0HY3+sdUzit7GAoxB1dCqB5PWsBb/jF/TpCVCRl5WcSewWCj4Djrk4V2k2712gBQpM7RvY/+aZcuQ6MCc9U0X8YYMBkk4NcJQLN6ivBD8TchwgDFlMfMSTGspspq6Km/UXTNjU2FcP4mSsxyGTlvUwjF7J5chTqp7VaYERvoP6zxVWbNhpRXKQIl9L7mMNXDLNZGoJ+sCf5AtqPL5menzKh6eYg1DvDSbU+4GKTevgBDIpBzD8AFMIKPJy7PWGvthD09wKYVggWuSfkJFDYI5jHSnj/mNELYwHO2v7mnkz0NpqwlApJZug==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: todo-app
    type: kubernetes.io/dockerconfigjson
