---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/part-of: todo-app
spec:
  encryptedData:
    .dockerconfigjson: AgBA+660DYOBpcigt3/SKxyf2xvZVGBaEIiEyj+afKfeQbu/lb7rXp/g81uKjfBnTFfh3f2/Di89BlYTQXFQ/kyjnap05c5wMzkA4O7wdlbnBM786KechZC4AS6Pu3jqXRZjflxfJkL2lFIV0WY6Idh3OwsVdgm4IYZA9TxSy46dx5zQccobK783ZNoY265Wzuvl7QhxJTxk9LWZiqyiSfkJQN55AcPB/EMK7V6VtSFe22fWmYVtozo6oPl8hz0pbRDboAae54K4nWm/NeGTMa3Fu3EQpLDAfxVs+eJFM88J0Pta64g191ZCtz4qo7fze+H3cX6Nj2GV+9rKfu7yBr68zaWxXTEsBxGqmdojVN7pR77UZN/qTTGwAs5yRoodJudlQR1VXjqYm7oHxwg7vznr/IZyIB9BDbKAi3he+3sntFqdN+5G+NnO0OLUmAokfwE9HaIXccynI8b55OTuCHd6XlyX42lsyS0UKlqDZV/wiYqdJkkPtDV8Og2OKqKx+dY8SpcN1x8MIkZ5NdWNgOZCJszj1x4zfBrQxH86OgHNiRgWKNOw8cvmgHh+2YEFR9ppP9ByWeQV6Sf1VcfLJ9K00QaEy68lxf4Y73pqacP/UT/PTVBuk9QnkBb8RmHOkNvCJLt3YHXeP68TLg6ge5RIkidbKO577qnxKcJIJOtZwRFNgqlNHKzZKmqBpJ8EJWKAgKWj6Sx4s2078wIslhyDkxQ94qzTWiO0zD2hn/CZCcJnTsfVudv8JyZckiEmGj9eU6cYZXF44saSs/tG1LqHwTDIiw9jFgIg9+/mlK5JeqeA/qF/oyscLmILf5gzcwAC7sCSSOdCBW9I3wNjQqhj9rrp6k4afk+buITxSrB/xflt6dTvO5ARlzim79X1UZXXR0Lhh2aEfI8d3gZCyTD/RpE12Kbk0iKx8UxIcDi2YQbZ49NEBtZ0xXqXhkzILai4pjwMsdnjadCp1dxTOJu6MIDHqM+b5+3Z/cmWp9OJ8T8=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: todo-app
      labels:
        app.kubernetes.io/name: todo-app
        app.kubernetes.io/part-of: todo-app
    type: kubernetes.io/dockerconfigjson
