---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: todo-app
spec:
  encryptedData:
    password: AgB4q7wxAY/eupZnZiF2jx05f60ZeCQQJESfxhOJ6daqfVcEnkEMsU9QwqkUu+p0TTNMhrblcgV+eK7vgrrrg2d85/1jms7gC4d6DqT7hc8hT8lZ1tCz7Fnu8HMF3bh5kZyVKdp/fgF+qv+cvrv3Ihea/cXZhulcwTZCkZaROB8V75FeFVeP6/3F4LcuD6skTLLtc/yT10ikfhl/wx9LZiChvvmmuRMe5tbPFbSYJW2JJkreYGXHvOr6nTftXSJp2ZM1/M3H00zHma1CBXXgOWfvTA3YLug/p9EDFVlhD3QXPJ3IYElIQKeFfXUl6hir0R28BWeNdNLQzrTiSexv3YqyD3vTHsd0Phctx68Y1dmUtbyuHYolEh9pLQBi/IWcVllH176DxQ+jYC+XJ3ABI7TA/oA9HAIXZTPOncunVG7aB4QUBBQK0jvNvT3sPzUXC6T7i2yKdG0gdDdeOuhTkHAQ6/LXbNBbvvYUcxH9C3LU27MngLgZyuOI5hdwYXxDNW7DpAJTUzxg/7NQ2CSTXpG0pf8TkxCxu1eo3oRNncpXpXgVPQmJm/ju89A7OB6wf9J/L84OvHS2Z51AnoZ/2A1JkT5nSA5MjOzhHxabAnZrsv55bLiW3a55z5hp2jsmBeuVVr5DPd70Qmrev2HVPg5sjBDMdGDzEivU4ylTMhHu/jp/C4aGZMFWoPed/KpYth1mYwAY0f/W2RDcu8TualjuHgPZrdrVMsLfZmiVG9AFqh5/mRj68USLceYfkw==
    username: AgAZzdVqZHrMhv3yTiB0Hg5D+vnvaMk4HKWcsaoUftvqqXO69Us/jqoEGaBQ7LU7VvYoKM2dahV2VQ6fUB0Iu1xcmHaKbRRcgqJwtHfRx+WPGW2SS5PkoAApLbl4ju8PcUIJP1pTv5n+siwCqI2/PxqgKYUVAGqbKQyjBjMKTru/GQ8kcAXUWj6ptYXvgxGdtq2m02RV+G5qtS+hGUFJsRywg2V50eJgCHmyUvINxa5qajGF/M5zekIDwCJkujCxeo9skLmzR+8CTxHXU9ByLxE2DBRGern3BbcmzAXTDbeYAEfWgFiB0rsU5sQmpARs009LL+4UuaUgWAJmZRat9A7x7mc1qkJ42KmOzxUlaK9+kRZ29B5ltz1/ydo5+Qit4nBiJ4SAHv55svXNOi/0DLyeeB5IF+1dKgOjG2nTywXwfLeqxDfr3tBn4BlBM12dWMMfIPzQ08ukxCC5mzLXQyYKgp2sxV47LraxOsLieKKwBd8w/Mr1JhWn59nezB3HVudUoDxZJgJI4dx1601Bb4EyxHmugW3t+v+Kpao0HCxt13yuAAMGcdV7X7BeHxsjCyiGDJDKWkyI/ggOJIQ4idQedeSB6+Q1H/j0t6xSEynoM1LW4mltka77JYalHCDXllreamPFC7D8SKWnz/X5nHQMT8umlZRb+6Ou2LFStHPCdd8OWq++o783UfNZU1J2bv8ehTZZs39f
  template:
    metadata:
      name: postgres-secret
      namespace: todo-app
    type: Opaque
