---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: todo-app
spec:
  encryptedData:
    db-password: AgAfO18RAtuISpjSufMChj4zmGXtgpRsfvUj9APQ0EaO7yWN92xPe3smuADBlKvtCAtBgTl42MAc8mOd3mXJzabqDLcq4q/IYG6w/4llYKnm8/jf1k1k8w87Zo5djRAobAoz28XFoKsab2kJJ7wL18YkXK7iszvKL0/+xYiKdRGOemKOn0IReYZAAeiJGMlSC4Qi9W3ASd8wR7I636tNQ3l4r2N53n9Qoz9YUkuI4yQZltokMcOvs6mbeXGAqsgsEXTS6hMdKST+RDtfFFdZ6buls10Sy5UrfunOjGFm6YUo/SVKikDfOIV7qRJ+iM03eM+8yFKfzEtUylqQ0i9HPQNTpHS8KcXTxfABFbMHT4jnu4UCo3fhfZiCUgiKKc5VQMy54gSF0pcfjlAdxfv5Ue3JWJZKvI3Utn7B32qvPjzs31lerMgf3nPAH/EjKLHc1XsGh/rYRAMWF8LI2+TLN0Hb3hN/eeFFDvozGwlpzIYTxV0KZ4tp/WhH+XDTRt0RbG+vNN8poy9/RqlPKdX4UaEr5sFiNuekhcpek13ETn08DwSrVot8cTx7dmhyQCTEWAaP53+ybM/a53PjiMeo2ID5WC4JCdlouKkgQtRSp3PtjTil4Px3R+Z0D7ewBUO6jzkYK4Mkba1DK7Efspov5APO7W6xZxsR6yfsRw7RPdh2CooJrBodLf9veIIjUGrbmnXOOF77byO7PI0EF2QS+/zOEm4J1JBD783c7qJAjtzTJ4Fc72oZIwQVp91R2Q==
    jwt-secret: AgCrK/SZT1gtfpkJrx4RwfrDActiq6eaNXhp4IRSZv+mc7kg0fNcpVI7lzoQiMkltzPh2Z0Rnebg8ep9qqhbJoh158MWTjBoajn4qLRjNNtrDVoJLyTsmBXhSO1+zsH5Kt1Y0rAIxJ3b8JYqekHxENbjP7ybPqSybI4z7HTTgphvC2DiU8zWoaHLZVKXrVZi7opzNqHl3jGKaw3TxIHjUjvpc8Cd+GmjrZXJiwuuz7EYQtUY2M7Mf3qhINmv6PeOxM1uAB+DtNOuHUx6ukNsy12MI8aW8Z4xUyYsH/iAWDpdbCc0LTT4Ia4oRY1HjrHrigvvOSgEsXRhncMYZg44V4g2bMNCcvoo2F4Urnj8UGrTzVyOxRopXKMZiqinQjJvSAmQFn4ekFimPbZv304x5qHExM81kcnB3eMm+piyCdtFA6elLq3mAbWFEl3iegRpto7XK4sm/m+5FaXx971F1QUMjPL+ipR9GdFSk86tR8UwmSTd5dLwthvdJ+g8OxVEJbCdtU9+iLCciFGEvMhlOiMXLQoTWjtUsBl2zaMIU9P0q5pmhkej8hEqfxpBq/BZye2Ph9iD70LAEvwSJffc1CXP985TQ3btLgV1vd1Yz4EyTIQNceA/rfgSRXWdxGwMuUutpGn9AJtYefGrh0icmFXbhTw2dbYqlxX1d0EzQyplIdWMzuY/B+afbgEQF1MEj2HpD3Bx6g/8m3bmA6eboeNICwZhKrx+tycbsmBrkcK7RQjFLXPRUscLdLM/rQ==
    mail-password: AgCV8QlnXzuivGAGOkeeV05iKxt86GDWUQiTZFVdBJjeI9yqFpOeQCzqRgyLsprsTVR5LwqdHQwpdYfRDtL6PkywfLLVxDPti/yR0CtCtsVIEEmI+IxFUxjM3L8srWP/6fide3sFyE3PaaUUHw0254o1yoq4XeMUOd4CmZ1ovYjg0Mx2tq5TFMqT/VamRFU+IGNlqo5WSP41pWaWRRk0vzy6NNPoIwITjUgMM/YzDNYekecMn/1t6mYvP/Jeg3ZjCSAUHkVsAb9TrjkNUkLqlNXO9vJqQS66pDD06BD27XWmse7yL5roScXSOHHNAMDNmVV1IbeOsV+LBgKT4TE3qhqKXafGlkBtgpvXKhoXMu4V4bUAFs4nkLu+G4rGgzMNhLQhGxCroceaFzMv+cMlpFueih/CCjUa/SGmJPzMYkN+MJjXM5Em9IsnSgZHwTJutB/+fVAiRCTsiZ7viIo7kznPg3s0b+cCy1zKi43N0pr71+1AM1zfAj14v+FBx/HrqvQ2ovYHrzqaT1EqnPRH5O3Np0z9oVT7OaDEGYnA5+fd6+/wTYkuHaRKmAp2KIE9y9ghy9R8RlKf7HrAh85/FxUNiusB0J+rFjLah9+7DSNSLCm+itE6Td4udxv4nJfj5qHg23TDKxA6YuKB9DmEe7Sg1iVCoL5Hz3zMM6+TS7pNuSi1iGSZ9XC+5YPe3Lg7ADTACHXg8gJUy9tYG4Vm6ZDc3EdiJxQOpIltGs0WddRTvbVrrfem4LVHJ5RH+u2h8RCldA==
  template:
    metadata:
      name: backend
      namespace: todo-app
      labels:
        app.kubernetes.io/name: todo-app
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: todo-app
    type: Opaque
