apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: todo-app
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/component: mail-server
    app.kubernetes.io/part-of: todo-app
spec:
  selector:
    app.kubernetes.io/component: mail-server
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
    - name: http
      port: 8025
      targetPort: http
