/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign up for a new account */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email with token */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's todos */
        get: operations["listTodos"];
        put?: never;
        /** Create a new todo */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todo identifier */
                id: number;
            };
            cookie?: never;
        };
        /** Get a single todo */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        /** Delete a todo */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        /** Partially update a todo */
        patch: operations["updateTodo"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TodoResponse: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example Buy groceries */
            title: string;
            /** @example false */
            completed: boolean;
            /**
             * Format: date-time
             * @example 2026-04-28T10:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2026-04-28T10:00:00Z
             */
            updated_at: string;
        };
        CreateTodoRequest: {
            /** @example Buy groceries */
            title: string;
        };
        UpdateTodoRequest: {
            /** @example Buy groceries */
            title?: string;
            /** @example true */
            completed?: boolean;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example s3cr3t!! */
            password: string;
        };
        SignUpRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example s3cr3t!! */
            password: string;
        };
        SignUpResponse: {
            /** @example Verification email sent. Check your inbox to verify your account. */
            message: string;
        };
        VerifyRequest: {
            /** @example 550e8400-e29b-41d4-a716-446655440000 */
            token: string;
        };
        AuthResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /**
             * @description Token validity in seconds
             * @example 3600
             */
            expires_in: number;
        };
        Problem: {
            /**
             * Format: uri-reference
             * @description A URI reference identifying the problem type. Use "about:blank" for standard HTTP errors; omit if not extending the type.
             */
            type?: string;
            /** @description A short, human-readable summary of the problem type. */
            title?: string;
            /** @description The HTTP status code. */
            status?: number;
            /** @description A human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description A URI reference identifying the specific occurrence.
             */
            instance?: string;
        };
        ValidationError: {
            /**
             * @description Error message for this field
             * @example must be a positive integer
             */
            detail: string;
            /**
             * Format: json-pointer
             * @description JSON Pointer to the offending field
             * @example #/age
             */
            pointer: string;
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: components["schemas"]["ValidationError"][];
        };
    };
    responses: {
        /** @description Missing or invalid Bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Missing or invalid Bearer token."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The authenticated user does not own this resource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "detail": "You do not have permission to access this todo."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Not Found",
                 *       "status": 404,
                 *       "detail": "Todo with id 42 was not found."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request body failed validation */
        UnprocessableContent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.todo.dangdoan.com/validation-error",
                 *       "title": "Your request is not valid.",
                 *       "status": 422,
                 *       "errors": [
                 *         {
                 *           "detail": "must not be blank",
                 *           "pointer": "#/title"
                 *         },
                 *         {
                 *           "detail": "size must be between 3 and 50",
                 *           "pointer": "#/username"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Internal Server Error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred. Please try again later."
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description User registered, verification email sent */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUpResponse"];
                };
            };
            /** @description Email is already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Conflict",
                     *       "status": 409,
                     *       "detail": "Email 'user@example.com' is already taken."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["UnprocessableContent"];
            500: components["responses"]["InternalServerError"];
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Email verified successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid or expired verification token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "about:blank",
                     *       "title": "Bad Request",
                     *       "status": 400,
                     *       "detail": "Verification token is invalid or expired."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["UnprocessableContent"];
            500: components["responses"]["InternalServerError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials or email not verified */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["UnprocessableContent"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listTodos: {
        parameters: {
            query?: {
                /** @description Filter by completion status */
                completed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of todos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoRequest"];
            };
        };
        responses: {
            /** @description Todo created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableContent"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todo identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todo identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todo identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoRequest"];
            };
        };
        responses: {
            /** @description Todo updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableContent"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
