apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: todo-app
data:
  DB_URL: jdbc:postgresql://postgres-service:5432/todoapp
  MAIL_HOST: mailhog-service
  MAIL_PORT: "1025"
  MAIL_SMTP_AUTH: "false"
  MAIL_SMTP_STARTTLS: "false"
