apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: todo-app
spec:
  selector:
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
