apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cert-manager/cluster-issuer.yaml
  - argocd/application.yaml
  - argocd/configmap.yaml
  - argocd/ingress.yaml
  - headlamp/ingress.yaml
  - secrets/sealed-postgres-secret.yaml
  - secrets/sealed-backend-secret.yaml
  - secrets/sealed-ghcr-pull-secret.yaml
images:
  - name: ghcr.io/dangongithub/todo-app/backend
    newTag: edge
  - name: ghcr.io/dangongithub/todo-app/frontend
    newTag: edge
patches:
  - path: patches/backend-configmap.yaml
  - path: patches/backend-deployment.yaml
  - path: patches/frontend-deployment.yaml
  - path: patches/backend-ingress.yaml
  - path: patches/frontend-ingress.yaml
